name: build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Java
        if: "!startsWith(matrix.os, 'windows')"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        if: "!startsWith(matrix.os, 'windows')"
        run: chmod +x gradlew

      - name: Build Native Image
        if: "!startsWith(matrix.os, 'windows')"
        run: |
          ./gradlew nativeImage --info
          chmod +x build/graal/Cloudchains-SPV
          rm -f build/graal/Cloudchains-SPV.build_artifacts.txt

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: native-image-${{ matrix.os }}-amd64.zip
          path: build/graal/Cloudchains-SPV

  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Download Artifacts (Ubuntu)
        id: download_artifacts_ubuntu
        uses: actions/download-artifact@v2
        with:
          name: native-image-ubuntu-latest-amd64.zip
        continue-on-error: false

      - name: Download Artifacts (macOS)
        id: download_artifacts_macos
        uses: actions/download-artifact@v2
        with:
          name: native-image-macos-12-amd64.zip
        continue-on-error: false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v5.1.12
          release_name: Cloudchains-SPV v5.1.12
          draft: false
          prerelease: false
          
      - name: Upload Release Assets ubuntu
        id: upload_release_assets_ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./native-image-ubuntu-latest-amd64.zip
          asset_name: native-image-ubuntu-latest-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Assets macos
        id: upload_release_assets_macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./native-image-macos-12-amd64.zip
          asset_name: native-image-macos-12-amd64.zip
          asset_content_type: application/zip


