name: build_ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    uses: ./.github/workflows/build_latest.yml
    with:
      branch: ${{ github.ref }}
      build_type: "artifacts"
      tag: "0.5.13"
