name: Build

on:
  push:
    branches:
      - dev-build-linux-amd64
  pull_request:
    branches:
      - dev-build-linux-amd64
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRAALVM_VERSION: 22.3.2

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Install GraalVM
      run: |
        curl -LJ "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.2/graalvm-ce-java17-linux-amd64-22.3.2.tar.gz" -o graalvm.tar.gz
        
        sudo mv graalvm-ce-java17-$GRAALVM_VERSION /usr/local/graalvm
        echo "/usr/local/graalvm/bin" >> $GITHUB_PATH

    - name: Inspect File Type 
      run: file graalvm.tar.gz

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew clean
        ./gradlew build

    - name: Build Native Image
      run: |
        ./gradlew nativeImage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: native-image-ubuntu-amd64
        path: build/libs/
