name: Build_windows

on:
  push:
    branches:
      - dev-build-linux-amd64
  pull_request:
    branches:
      - dev-build-linux-amd64
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Windows SDK 10
      run: |
     #   choco upgrade chocolatey
        choco install windows-sdk-10 -y

    - name: Build Native Image
      run: |
        # Set the path to the installed Windows SDK 10
        $sdkPath = "C:\Program Files (x86)\Windows Kits\10"
        # Add the SDK bin directory to the PATH
        $env:Path += ";$sdkPath\bin"
        # Run the nativeImage task using the installed SDK
        .\gradlew.bat nativeImage --stacktrace

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: native-image-windows-amd64
        path: build/graal/
