name: Build

on:
  push:
    branches:
      - dev-build-linux-amd64
  pull_request:
    branches:
      - dev-build-linux-amd64
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Windows SDK 7.1
      run: |
        choco install windows-sdk-7.1 -y
    - name: Build Native Image
      run: |
        .\gradlew.bat nativeImage --info
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: native-image-windows-amd64
        path: build/graal/
