name: Build_windows

on:
  push:
    branches:
      - dev-build-linux-amd64
  pull_request:
    branches:
      - dev-build-linux-amd64
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install Visual Studio Build Tools 2019
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vs-path: '2019'

      - name: Install Windows SDK 10
        run: choco install windows-sdk-10 -y

      - name: Create environment file
        run: |
          echo "SDK_PATH=C:\Program Files (x86)\Windows Kits\10" >> $GITHUB_ENV
          echo "PATH=$env:SDK_PATH\bin;$env:PATH" >> $GITHUB_ENV
          echo "LIB=$env:SDK_PATH\Lib;$env:LIB" >> $GITHUB_ENV
          echo "INCLUDE=$env:SDK_PATH\Include;$env:INCLUDE" >> $GITHUB_ENV

      - name: Build Native Image
        run: ./gradlew.bat nativeImage --stacktrace

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: native-image-windows-amd64
          path: build/graal/
