name: Build_windows

on:
  push:
    branches:
      - dev-build-linux-amd64
  pull_request:
    branches:
      - dev-build-linux-amd64
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Windows SDK 8.0
      run: |
        choco upgrade chocolatey
        choco install windows-sdk-8.0 -y

    - name: Build Native Image
      run: |
        # Set the path to the installed Windows SDK 8.0
        $sdkPath = "C:\Program Files (x86)\Microsoft SDKs\Windows\v8.0A"
        # Add the SDK bin directory to the PATH
        $env:Path += ";$sdkPath\Bin"
        # Set the path to the SDK include directory
        $env:INCLUDE = "$sdkPath\Include;$env:INCLUDE"
        # Set the path to the SDK lib directory
        $env:LIB = "$sdkPath\Lib;$env:LIB"
        # Run the nativeImage task using the installed SDK
        .\gradlew.bat nativeImage --stacktrace

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: native-image-windows-amd64
        path: build/graal/
