name: Build_windows

on:
  push:
    branches:
      - dev-build-linux-amd64
  pull_request:
    branches:
      - dev-build-linux-amd64
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Batch File
      shell: cmd
      run: |
        call nativeImageWindows.bat

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
         name: native-image-windows-amd64
         path: build/graal/
